- name: Retrieve {{ item }} package build from brew
  shell: |
    brew list-builds \
      --package={{ iib_operator_spec[item].package_name }} \
      --state=COMPLETE --quiet | grep v{{ iib_operator_spec[item].version_matrix[iib_ocp_version] }} \
      | sort -V | tail -1 | awk '{print $1}'
  register: brew_build

- name: Retrieve {{ item }} bundle image from package build
  shell: |
    brew --noauth call \
      --json getBuild \
      {{ brew_build.stdout }} | jq -r '.extra.image.index.pull[0]'
  register: bundle_image

- name: Add {{ item }} bundle to index image
  shell: |
    opm index add \
      --bundles {{ bundle_image.stdout }} \
      {% if not ansible_loop.first %}
      --from-index {{ iib_registry_hostname }}:{{ iib_registry_port }}/{{ iib_registry_namespace }}/{{ iib_catsrc_image_name }}:v{{ iib_ocp_version }} \
      {% endif %}
      --tag {{ iib_registry_hostname }}:{{ iib_registry_port }}/{{ iib_registry_namespace }}/{{ iib_catsrc_image_name }}:v{{ iib_ocp_version }}

- name: Push index image to registry
  shell: |
    podman push {{ iib_registry_hostname }}:{{ iib_registry_port }}/{{ iib_registry_namespace }}/{{ iib_catsrc_image_name }}:v{{ iib_ocp_version }}
