# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

FROM centos:7 AS builder

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy
ENV DPDK_FILENAME=dpdk-22.11.1.tar.xz
ENV DPDK_LINK=http://fast.dpdk.org/rel/${DPDK_FILENAME}
ENV RTE_SDK=/root/dpdk-stable-22.11.1/
ENV RTK=4.18.0-372.40.1.rt7.197.el8_6.x86_64
#ENV RTK=4.18.0-305.34.2.rt7.107.el8_4.x86_64

WORKDIR /root/
COPY /files /root/files
RUN yum update -y
RUN yum install -y gcc-c++ make git xz-utils wget numactl-devel epel-release && yum install -y meson python3-pip
RUN pip3 install pyelftools

RUN wget $DPDK_LINK
RUN tar -xf $DPDK_FILENAME 

# RT repo
#RUN wget http://linuxsoft.cern.ch/cern/centos/7.9.2009/rt/CentOS-RT.repo -O /etc/yum.repos.d/CentOS-RT.repo
#RUN wget http://linuxsoft.cern.ch/cern/centos/7.9.2009/os/x86_64/RPM-GPG-KEY-cern -O /etc/pki/rpm-gpg/RPM-GPG-KEY-cern

# install kernel sources to compile DPDK
#RUN export isRT=$(uname -r | grep rt -c) && if [ $isRT = "1" ] ; then yum install -y "kernel-rt-devel-uname-r == $(uname -r)"; else yum install -y "kernel-devel-uname-r == $(uname -r)"; fi
RUN yum localinstall files/kernel-rt-devel-${RTK}.rpm -y
RUN mkdir -p /lib/modules/${RTK}
RUN ln -s /usr/src/kernels/${RTK} /lib/modules/${RTK}/build

RUN cd $RTE_SDK && meson build && cd build && ninja

FROM centos:7.9.2009

ENV RTE_SDK=/root/dpdk-stable-22.11.1/

WORKDIR /root/
RUN yum install -y numactl-devel python3
 
COPY --from=builder /${RTE_SDK}/app/test-bbdev/test-bbdev.py .
COPY --from=builder /${RTE_SDK}/app/test-bbdev/test_vectors/ .
COPY --from=builder /${RTE_SDK}/build/app/dpdk-test-bbdev  .

