#@follow_tag(registry.redhat.io/ubi9/ubi-minimal)
FROM registry.redhat.io/ubi9/ubi-minimal:9.2-484

LABEL com.redhat.component="dpdk-base-container" \
    name="dpdk-base" \
    version="v4.13.1" \
    summary="dpdk-base" \
    io.openshift.expose-services="" \
    io.openshift.tags="< tags >" \
    io.k8s.display-name="dpdk-base" \
    io.openshift.s2i.scripts-url=image:///usr/libexec/s2i \
    io.s2i.scripts-url=image:///usr/libexec/s2i \
    description="dpdk-base"

ENV \
    APP_ROOT=/opt/app-root \
    # The $HOME is not set by default, but some applications needs this variable
    HOME=/opt/app-root/src \
    PATH=$PATH:/opt/app-root/src/bin:/opt/app-root/bin \
    PLATFORM="el9"

ENV BUILDER_VERSION 0.1
ENV DPDK_VER 22.11-3-test
ENV DPDK_DIR /usr/share/dpdk
ENV RTE_TARGET=x86_64-default-linux-gcc
ENV RTE_EXEC_ENV=linux
ENV RTE_SDK=${DPDK_DIR}

RUN INSTALL_PKGS="bsdtar \
  findutils \
  groff-base \
  glibc-locale-source \
  glibc-langpack-en \
  gettext \
  rsync \
  scl-utils \
  tar \
  unzip \
  xz \
  yum \
  make \
  rdma-core \
  libibverbs \
  git \
  gcc \
  meson \
  expect" && \
  mkdir -p ${HOME}/.pki/nssdb && \
  chown -R 1001:0 ${HOME}/.pki && \
  microdnf install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
  rpm -V $INSTALL_PKGS && \
  microdnf -y clean all --enablerepo='*'

COPY dpdk-test-rpms /opt
RUN dnf install -y /opt/dpdk-22.11-3.el9.x86_64.rpm \
   /opt/dpdk-devel-22.11-3.el9.x86_64.rpm \
   /opt/dpdk-tools-22.11-3.el9.x86_64.rpm && \
   rm -rf /opt/dpdk-*.rpm
#    
##
## in dpdk 20.11 the testpmd bin changed to dpdk-testpmd
## for backport support we add a symlink
RUN ln -s /usr/bin/dpdk-testpmd /usr/bin/testpmd

# Directory with the sources is set as the working directory so all STI scripts
# can execute relative to this path.
WORKDIR ${HOME}

# Reset permissions of modified directories and add default user
RUN useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin \
      -c "Default Application User" default && \
  chown -R 1001:0 ${APP_ROOT}
